### ISSUE TITLE
Link Number error

### ISSUE THREAD

**Issue by HowardBaxton** [nPoseTeam/Prim-Params-Editor-plugin#2]
In the nPose Prim Params Editor plugin, main V1.00.lsl the function "getLinkNumberList()" always returns link number 0 in a single prim build, even when an AV is linked to the prim.  This does not follow with "llGetLinkNumber( )" as the link number changes from 0 to 1 when someone is seated.  The script fails when seated but works fine when standing.

**Comment by LeonaMorro** [comment]
Please verify if the current version in the master branch still contains this error. Because I think this could already be fixed with the commit 7cdeff5facc5142dee712e547d077ae58c925602. I guess I simply forgot to release the new version.

**Comment by HowardBaxton** [comment]
hmm... my bad.  I am pretty sure I downloaded the newest version but it seems I did not.
